# Generated by Django 3.1.2 on 2020-11-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=25)),
                ('accname', models.CharField(max_length=30)),
                ('accpassword', models.CharField(max_length=11)),
                ('date', models.DateField()),
            ],
        ),
    ]
