# Generated by Django 3.1.2 on 2020-11-03 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passsecure', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='index',
            new_name='secure',
        ),
    ]
