# Generated by Django 3.1.2 on 2020-11-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passsecure', '0002_auto_20201104_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secure',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
