# Generated by Django 3.1.2 on 2020-11-07 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passsecure', '0003_auto_20201105_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='usertable',
            fields=[
                ('userid', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25)),
                ('userpass', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='secure',
            name='userid',
            field=models.IntegerField(default=1, verbose_name=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='passsecure.model', verbose_name='')),
            preserve_default=False,
        ),
    ]
